#ifndef SYSTEMCLOCKHANDLER_CONFIG_H_
#define SYSTEMCLOCKHANDLER_CONFIG_H_

#define SYS_HAN_HSE_VALUE		SYS_HAN_CLOCK_8MHz
#define SYS_HAN_MAX_SYS_CLOCK 	SYS_HAN_CLOCK_72MHz

#endif /* SYSTEMCLOCKHANDLER_CONFIG_H_ */
