#include "STD_TYPES_H.h"
#include "GPIO_Interface.h"
#include "LEDHandler_Interface.h"
#include "LEDHandler_config.h"

const LEDHandlerConfigType ledsConfig[NUMBER_OF_LEDS]=
{
		{LEDH_PP_MODE,LEDH_50M_SPEED,LEDH_C_PORT,LEDH_PIN_13,LEDH_STATE_OFF,LEDH_ACTIVE_STATE_LOW},
		{LEDH_OD_MODE,LEDH_10M_SPEED,LEDH_A_PORT,LEDH_PIN_2,LEDH_STATE_ON,LEDH_ACTIVE_STATE_HIGH},
		{LEDH_PP_MODE,LEDH_2M_SPEED,LEDH_C_PORT,LEDH_PIN_0,LEDH_STATE_OFF,LEDH_ACTIVE_STATE_HIGH}
};
