#ifndef USART_CONFIG_H_
#define USART_CONFIG_H_

#define BAUDRATE_CONFIG USART_BAUDRATE_9600
#define PARITY_CONFIG	USART_PARITY_DISABLE
#define STOP_CONFIG		USART_STOP_1

#endif /* USART_CONFIG_H_ */
